---
- hosts: vault_nodes
  become: yes
  roles:
    - vault_install

- hosts: Auto_Unseal_Provider
  become: yes
  roles:
    - vault_config
    - vault_init
    - vault_auto_unseal_setup

- hosts: Vault_Master
  become: yes
  roles:
    - vault_config
    - vault_validate

# - hosts: vault_followers
#   become: yes
#   roles:
#     - vault_config

# - hosts: Vault_Master
#   become: yes
#   roles:
#     - vault_validate
